### ISSUE TITLE
Listing testnets is not supported

### ISSUE THREAD

**Issue by atoulme** [Whiteblock/genesis#22]
**Describe the bug**
The API docs mention you can do `GET /testnets` and get the list of testnets.
However performing this action returns a 405 error.

**To Reproduce**
```
curl -X GET -H "accept: application/json" http://localhost:8000/testnets -vv
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /testnets HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.47.0
> accept: application/json
> 
< HTTP/1.1 405 Method Not Allowed
< Date: Thu, 09 May 2019 23:14:21 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

**Comment by n8wb** [comment]
Support for that was actually removed a couple weeks ago, because, well, it is confusing. It used to list all of the testnets which were built with this client, which just consisted of testnet id and the blockchain name. Sorry for any confusion as we updated the documentation. Is there something you needed from it in particular?

**Comment by atoulme** [comment]
It's just that you give the testnet id exactly once on creation, and is returned as the body of the response of the POST request. It would be good to be able to query for it again.

**Comment by zscole** [comment]
Thanks for this feedback, @atoulme. I completely agree and this is something brought up the other day, so let's push the ball on this because I don't think it would be terribly difficult to implement.

**Comment by n8wb** [comment]
Ah, I see. Actually there is another call which is in the works for this. Which is to get the last build.

**Comment by n8wb** [comment]
To get the previous build, you can now use `GET /build`
