### ISSUE TITLE
Cannot run artemis blockchain

### ISSUE THREAD

**Issue by atoulme** [Whiteblock/genesis#24]
**Describe the bug**
When I try to run the artemis blockchain, the program complains it cannot comply as it tries to download a docker image that requires authentication.

This issue comes from this code in `artemis/conf.go`:
```
func GetServices() []util.Service {
	return []util.Service{
		{
			Name:  "wb_influx_proxy",
			Image: "gcr.io/wb-genesis/bitbucket.org/whiteblockio/influx-proxy:master",
			Env: map[string]string{
				"BASIC_AUTH_BASE64": base64.StdEncoding.EncodeToString([]byte(conf.InfluxUser + ":" + conf.InfluxPassword)),
				"INFLUXDB_URL":      conf.Influx,
				"BIND_PORT":         "8086",
			},
		},
	}
}```

**Comment by atoulme** [comment]
Is this docker image special `gcr.io/wb-genesis/bitbucket.org/whiteblockio/influx-proxy:master` ?
Or can we use one that is publicly available?

**Comment by n8wb** [comment]
I rebuilt it in a publicly available place and updated it in the code. It is now at  gcr.io/whiteblock/influx-proxy:master.
