### ISSUE TITLE
Make `Blockchain` type 

### ISSUE THREAD

**Issue by decanus** [Whiteblock/genesis#3]
https://github.com/Whiteblock/genesis/blob/dev/manager/addnodes.go#L69 we have the `details.Blockchain` here which is a type string.

What could be done to reduce strings in the code and possibility for spelling errors is create a new type.

```go
type Blockchain string;
```

this type could then be used to defined constants for every blockchain eg:

```go
const (
    Ethereum Blockchain = "ethereum";
)
```

**Comment by n8wb** [comment]
I think that the new registrar setup handles this issue now, so I am going to close this. Although, in the future, it might still be a good idea to make a blockchain type.
