### ISSUE TITLE
Missing Important Logging Details

### ISSUE THREAD

**Issue by tueric** [Whiteblock/genesis#38]
I'm a big fan who is trying to get Genesis running. However, the lack of logging makes it difficult to play around with the software. My first roadblock was not knowing how to communicate with the daemon because there is no indication of what port the daemon is listening on.

**Comment by n8wb** [comment]
Thank you for the feedback! Incase anyone stumbles upon this, wondering the answer, it can be found [here](https://github.com/Whiteblock/genesis/blob/dev/config.json) under "listen", that is the socket on which genesis will listen. (Currently 127.0.0.1 port 8000)

**Comment by zscole** [comment]
> Thank you for the feedback! Incase anyone stumbles upon this, wondering the answer, it can be found [here](https://github.com/Whiteblock/genesis/blob/dev/config.json) under "listen", that is the socket on which genesis will listen. (Currently 127.0.0.1 port 8000)

This should be added to the Genesis output so it displays that address by default.

**Comment by n8wb** [comment]
More logging has been added and also the verbosity of the logs is now configurable via the env variable VERBOSITY or the verbosity field in the config file.
