### ISSUE TITLE
.travis.yml

### ISSUE THREAD

**Issue by decanus** [Whiteblock/genesis#69]
Change the travis file to have multiple jobs making `vet`, `lint` and `test` seperate runs where the former 2 can fail.

See example: https://github.com/ensdomains/ethregistrar/blob/master/.travis.yml#L9-L17

**Comment by n8wb** [comment]
`vet`, `lint` and `test` are required by design in order to encourage proper maintenance of the code base. We should not make them optional, as they help to keep the code clean in the case of `lint` and free of errors in the case of `vet`.

**Comment by decanus** [comment]
@n8wb you can still do them in seperate jobs though so they could run in parallel.
